### PR TITLE
refactored + made professional-er

### PR DESCRIPTION
**Pull request by CodeByAidan**
proof of it working:
image

```
C:\Users\aidan\OneDrive\Documents\GitHub\random-spotify-lyrics>python -u "c:\Users\aidan\OneDrive\Documents\GitHub\random-spotify-lyrics\main.py"
Fetching lyrics for Tainted Love by Soft Cell
Get away from the pain you drive into the heart of me
```

### CODE REVIEW

**Comment by timof121** [comment]
bro wtf

**Comment by timof121** [comment]
ok I'll merge later

**Comment by timof121** [comment]
the comments make the code look to messy and shit

**Comment by timof121** [comment]
bro the fucking code went from 39 lines to 101

**Comment by livxy** [comment]
> ok I'll merge later

men it's ben past 24 hour men

**Comment by timof121** [comment]
jaja

**Comment by livxy** [comment]
still waiting sir.
This branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branchThis branch has no conflicts with the base branch

**Review by CodeByAidan — COMMENTED** [review]
it's literally fine tf

**Pull request closed without merging**
